# Generated by Django 4.1.7 on 2023-03-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testtable',
            table='test',
        ),
    ]
